"""Shared physical constants for the tailwater client package.

These are the few server-side constants from `structure_io.py` that the
customer-facing code (`hr_export`, `subspace_utils`, etc.) needs to keep
in sync with whatever the API produced. Importing them through a
single module keeps the version known on both sides.
"""

import numpy as np


# Number of atomic-identity one-hot columns in node_features.
# node_features layout:
#   cols [0 : NUM_ELEMENTS]            = atomic-Z one-hot (109 elements)
#   cols [NUM_ELEMENTS : NUM_ELEMENTS+18] = orbital-active flags (18 channels)
NUM_ELEMENTS = 109


# Translation R-vectors indexed by inv_data[:, 2].
# NeighBrs[0] is the in-cell self-translation (0,0,0); the rest are the
# positive representatives of the first few coordination shells (the
# Hermitian conjugates -R are auto-generated by tbmodels from these).
# Must match what the API's server-side process_win produces.
NeighBrs = np.array([
    [ 0,  0,  0], [ 0,  0,  1], [ 0,  1,  0], [ 1,  0,  0],
    [ 0,  1, -1], [ 0,  1,  1], [ 1, -1,  0], [ 1,  0, -1],
    [ 1,  0,  1], [ 1,  1,  0], [ 1, -1, -1], [ 1, -1,  1],
    [ 1,  1, -1], [ 1,  1,  1], [ 0,  0,  2], [ 0,  2,  0],
    [ 2,  0,  0],
])
